# Generated by Django 5.2.8 on 2026-06-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_alter_favorite_options_alter_follow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
